import { AbstractCollectionView } from "./AbstractCollectionView";
import { AbstractItemView } from "./AbstractItemView";
import { LotusHTMLElement } from "../context/LotusHTMLElement";
import * as Lavender from 'lavenderjs/lib';
export declare class FormCollectionView extends AbstractCollectionView {
    static INPUT: number;
    static VALIDATION_ERROR: number;
    static SUBMIT: number;
    static ERROR: number;
    protected _state: number;
    protected _validationWarning: HTMLElement;
    protected _validationWarningDisplay: string;
    protected _inputState: HTMLElement;
    protected _inputStateDisplay: string;
    protected _submitState: HTMLElement;
    protected _submitStateDisplay: string;
    protected _errorState: HTMLElement;
    protected _errorStateDisplay: string;
    protected _input: HTMLElement;
    protected _list: HTMLElement;
    protected _radioGroup: HTMLElement;
    protected _file: HTMLElement;
    protected _error: HTMLElement;
    protected _errorDisplay: string;
    protected _submit: HTMLElement;
    protected _clear: HTMLElement;
    protected _back: HTMLElement;
    inputView: string;
    listView: string;
    radioGroupView: string;
    fileView: string;
    constructor();
    submit: HTMLElement;
    clear: HTMLElement;
    back: HTMLElement;
    error: HTMLElement;
    state: number;
    validationWarning: HTMLElement;
    inputState: HTMLElement;
    submitState: HTMLElement;
    errorState: HTMLElement;
    input: HTMLElement;
    list: HTMLElement;
    radioGroup: HTMLElement;
    file: HTMLElement;
    protected getModel(model: any): Object;
    protected createChildView(model: Object): AbstractItemView;
    protected cloneItemTemplate(model: any): LotusHTMLElement;
    protected clearErrors(): void;
    protected addErrors(errors: Lavender.ArrayList): void;
    protected onSubmit(event: Event): void;
    protected onClear(event: Event): void;
    protected onBack(event: Event): void;
    protected setUpViewBindings(model: Object, view: AbstractItemView): void;
    protected resolveState(state: number, oldState: any, errors?: Lavender.ArrayList): void;
    onError(error: Error): void;
    onReady(): void;
    defineSkinParts(): void;
    onSkinPartAdded(part: string, element: HTMLElement): void;
    destroy(): void;
}
